### ISSUE TITLE
This component need update for latest Kevoree

### ISSUE THREAD

**Issue by sdalgard** [barais/genericComponentModelRequester#1]
Is it possible to make this available in the repo for the latest Kevoree to be used at the HEADS review meeting?

**Comment by maxleiko** [comment]
Yes sure, but when I updated the code to comply with Kevoree 5.5.0-SNAPSHOT it revealed an issue in the KevScriptService that I'm fixing. I'll release the new Kevoree SNAPSHOT and the update of this component in one batch ASAP
